### ISSUE TITLE
건물 메뉴 트리구조 구성

### ISSUE THREAD

**Issue by universpace** [CSID-DGU/2020-1-CECD3-Generator-8#24]

**Comment by 0417yjy** [comment]
URL에 빌딩 번호랑 층 번호 있잖아. 이걸 가져와서 사이트 로딩할 때 자바스크립트로 CSS 빌딩 메뉴(해당하는 빌딩 번호로) 열고 현재 보고 있는 층 아이템에 대해서 하이라이팅하면 쉽게 가능할 것 같아
