### ISSUE TITLE
파일 추출 기능 변경(Export to file)

### ISSUE THREAD

**Issue by universpace** [CSID-DGU/2020-1-CECD3-Generator-8#25]
### 현재 Export to file:
> 현재 페이지의 로그테이블을 .csv파일로 추출

### 변경해야할 것:
> 1. 보고서로 만들어 관리자에게 전송.
> 2. 보고서로 만들어 저장.

**Comment by 0417yjy** [comment]
보고서 RPA 작성 스크립트가 먼저 있어야겠네

**Comment by universpace** [comment]
그러지 않을까 싶다
