### ISSUE TITLE
센서 값 그래프 개선

### ISSUE THREAD

**Issue by 0417yjy** [CSID-DGU/2020-1-CECD3-Generator-8#51]
현재는 x축의 시간값들이 단순 문자열로 되어 있음 -> 이를 실질적인 Date 값으로 인식하고 시간값으로 하여 누락된 센서 값은 같은 값으로 길게 늘여 개선

**Comment by 0417yjy** [comment]
지금까지의 구현은 유지하되, 마지막 로그가 3일보다 더 오래됐으면 딴거 안하고 마지막 로그를 현재 시간에 맞추어 회색 라인으로 하나 만드는건 어떨까? 그러면 로딩 시간도 줄일 수 있을 것 같은데

**Comment by universpace** [comment]
> 지금까지의 구현은 유지하되, 마지막 로그가 3일보다 더 오래됐으면 딴거 안하고 마지막 로그를 현재 시간에 맞추어 회색 라인으로 하나 만드는건 어떨까? 그러면 로딩 시간도 줄일 수 있을 것 같은데

때려쳤음 코드 너무 어려움

**Comment by 0417yjy** [comment]
마지막으로 누나가 고침
