### ISSUE TITLE
Monitoring 페이지의 Export to File 버튼 동작 변경

### ISSUE THREAD

**Issue by 0417yjy** [CSID-DGU/2020-1-CECD3-Generator-8#58]
* 현재: 페이지에 보이는 모든 행들을 긁어 하나의 csv파일로 만들어 다운로드
* 변경: 마지막 일일 보고서 이후에 나타난 모든 고장 현상을 모아 하나의 csv 파일로 다운로드  
-> 필요 시, DB 테이블 추가 혹은 변경 가능

**Comment by universpace** [comment]
이건 이슈 57이 해결되어야 할 수 있을거같은데

**Comment by 0417yjy** [comment]
> 이건 이슈 57이 해결되어야 할 수 있을거같은데

지금 해결해 드립니다

**Comment by 0417yjy** [comment]
석윤이형 요청. export시 건물과 층 정보도 함께 내줄 것

**Comment by universpace** [comment]
> 석윤이형 요청. export시 건물과 층 정보도 함께 내줄 것

OMG
