### ISSUE TITLE
적절한 상태 단어 선정

### ISSUE THREAD

**Issue by 0417yjy** [CSID-DGU/2020-1-CECD3-Generator-8#85]
* 현재는 BR(Broken) / TE(Temporary Error) / WN(Warning) / OP(Operational)

**Comment by 0417yjy** [comment]
[여기](https://www.paessler.com/manuals/prtg/sensor_states)에 따라서,  
Down / Unknown / Unusual(혹은 Warning) / Up 4개의 상태로 바꾸는게 어떨까.  
* Down: 값 안보냄
* Unknown: 아직 데이터를 못 받음 (네트워크 오류 등으로 인하여)
* Unusual(혹은 Warning): 받았으나 값이 이상함
* Up: 센서가 멀쩡함

**Comment by universpace** [comment]
> [여기](https://www.paessler.com/manuals/prtg/sensor_states)에 따라서,
> Down / Unknown / Unusual(혹은 Warning) / Up 4개의 상태로 바꾸는게 어떨까.
> 
> * Down: 값 안보냄
> * Unknown: 아직 데이터를 못 받음 (네트워크 오류 등으로 인하여)
> * Unusual(혹은 Warning): 받았으나 값이 이상함
> * Up: 센서가 멀쩡함

[여기](https://community.carbonblack.com/t5/Knowledge-Base/Endpoint-Standard-What-Do-The-Different-Sensor-Status-Options/ta-p/65438)에 나와있는거에서
Up->Active / Down->Inactive가 어떨지?
